version: '3'
services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    # Dodaj inne konfiguracje dla service1

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    ports:
      - 8002:8002